name: mm-hdc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pytorch-gpu
  - torchvision
  - scikit-learn
  - matplotlib
  - tqdm
  - ml-collections
  - absl-py

  # Testing
  - pytest

  # Needed for torch C++ extension build in hdc/__init__.py
  - ninja
  - gxx_linux-64
  - pybind11
